const sites = [
    {
        ID: "1",
        nom: "Goutte",
        type: "Eau",
        densité: "60",
        ressources: "40",
        danger_alentour: "14",
    },
    {
        ID: "2",
        nom: "Source",
        type: "Eau",
        densité: "70",
        ressources: "50",
        danger_alentour: "10",
    },
    {
        ID: "3",
        nom: "Rivière",
        type: "Eau",
        densité: "80",
        ressources: "60",
        danger_alentour: "20",
    },
    {
        ID: "4",
        nom: "Alpha",
        type: "Bunker",
        densité: "50",
        ressources: "70",
        danger_alentour: "30",
    },
    {
        ID: "5",
        nom: "Bravo",
        type: "Bunker",
        densité: "55",
        ressources: "75",
        danger_alentour: "25",
    },
    {
        ID: "6",
        nom: "Charlie",
        type: "Bunker",
        densité: "60",
        ressources: "80",
        danger_alentour: "35",
    },
    {
        ID: "7",
        nom: "Delta",
        type: "Bunker",
        densité: "65",
        ressources: "85",
        danger_alentour: "40",
    },
    {
        ID: "8",
        nom: "Station Électrique Espilon",
        type: "Electricité",
        densité: "90",
        ressources: "95",
        danger_alentour: "5",
    },
    {
        ID: "9",
        nom: "Station Électrique Zeta",
        type: "Electricité",
        densité: "85",
        ressources: "90",
        danger_alentour: "10",
    },
];

export default sites;